### ISSUE TITLE
Tutorial dev: Software installation

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#10]
- [ ] Please complete / extend learning goals where you see fit.
- [ ] Let us draft a "draaiboek" for a video to record, for both Mac users as well as Windows users [no Linux, right?]
- Let's wait for recording until we know the final set of packages we will be using in the class

**Comment by RoyKlaasseBos** [comment]
**Learning goals:** 
* Navigate the terminal and are familiar with basic commands (`pwd`, `ls`, `cd`, `pip install`)
* Understand the difference between absolute and relative file paths
* Install Python through the Anaconda installation 
* Install Jupyter Notebook through the Anaconda installation 
* Install Spyder through the Anaconda installation
* Create new Jupyter Notebooks
* Open Jupyter Notebooks from others (show example of downloading one from Github)
* Understand that cells run from top to bottom (and the potential issues that could cause)
* Know the difference between code and markdown cells
* Add and remove cells
* Interrupt and restart kernels
