### ISSUE TITLE
make sure selenium content works for the new version of selenium

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#109]
Selenium has recently been updated, with slight modifications to the syntax.

The deliverable of this issues are:
- [x] go through all tutorials of odcm that use selenium, and ensure that I use the __latest__ version of the syntax (it has something to do with the BY packages to search BY class, etc.)
- [x] go through all of the selenium content on Tilburg Science Hub and __also__ update the syntax there.

Contribute your new code via two PRs, one for TSH and one for oDCM.

**Comment by thierrylahaije** [comment]
@hannesdatta pages about selenium on tsh website have been edited. In the course I only found one place were the find_element class from selenium was being used and it was already corrected as it should be.
