### ISSUE TITLE
conduct SPA automatically (?)

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#110]
The SPA procedure now is very very manual:

- I manually fill in student team numbers on Canvas
- I export the team numbers and make a new google sheet
- Using the google sheet, I generate invitation links that I send out via email (takes about 2 hours)
- Students send in their evaluations; making the final grades + checking that everything went well takes another 1.5-2 hours. Per course.

In total, the SPA costs me 4 hours for each course, and I truly believe this needs to be smoothened a bit.

Any ideas?

**Comment by hannesdatta** [comment]
Deliverable: concept idea of how this would be technically realizable on Canvas, with infrastructure that will ultimately run in Tilburg and be GDPR-save.

- Possibility to have a prototype plugin

Pref is Python

**Comment by thierrylahaije** [comment]
To perform this task, I still have a couple additional questions.

1. Should the SPA be external or internal? (e.g. can the SPA be done via Canvas in a quiz or assignment or does the SPA need to be handled elsewhere as done currently in Dprep & ODCM)
2. I see that you manually fill in student team numbers on canvas, which already can be done automatically. Do you still want to do this manually or can this be automated as well?

Below you can find a diagram in which a possible solution is shown. The solution is based on the API of Canvas. This script can be written out in Python in combination with PycURL or another library that supports cURL. 

Two necessities to test the script are the following:

1. A development area for canvas needs to be realised.
2. An API-key is necessary when implemented. Canvas states that these API keys can also be received by teachers and administrators. 

<img width="2256" alt="Untitled" src="https://user-images.githubusercontent.com/65568251/202856886-564de6ad-f57c-4337-9440-e964ccb8ab1f.png">

**Comment by thierrylahaije** [comment]
Due to the fact that this project will currently not be followed up, this issue will be closed.
