### ISSUE TITLE
Create Tilburg `book` theme

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#18]
@andreantonacci; after the revision from @agemarks, can you please 

- [x] clone the original hugo book theme, and 
- [x] replace their book design with our updated tilburg design
- [x] keep the content of the basic book template as is
- [x] paste a raw course structure (on the basis of our sections: course, syllabus, etc in the EXAMPLE section of the page
- [x] update the readme of the book theme, and
- [x] release it under @tilburgsciencehub\open-education-template?

No rush on this, but let's get this done eventually so others can join soon.

Is end of Nov. realistic? 

Thanks.

**Comment by andreantonacci** [comment]
@hannesdatta Yes, I think it is. Will do.
