### ISSUE TITLE
Conceptual framework

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#19]
@RoyKlaasseBos, as discussed, would you be able to think critically about the framework, please?
[new_framework.pptx](https://github.com/hannesdatta/course-odcm/files/5537535/new_framework.pptx)

Maybe there are ways to improve it. Will become the backbone of course (and paper).

A few ideas to improve are enough for a start. Let's see what you can come up with.

**Comment by RoyKlaasseBos** [comment]
[2020_11_16_vertical_process_chart.pptx](https://github.com/hannesdatta/course-odcm/files/5548257/2020_11_16_vertical_process_chart.pptx)

Font: https://www.fontsquirrel.com/fonts/computer-modern

**Comment by hannesdatta** [comment]
Thanks a bunch, Roy. Do you see any option to make this horizontal? It will display much better in a paper or on a website.

My humble attempt:

![image](https://user-images.githubusercontent.com/16557730/99790697-c5a9f900-2b24-11eb-97b6-1c8cd5d76bce.png)

We need to keep it with Arial (JM style).

**Comment by RoyKlaasseBos** [comment]
> Thanks a bunch, Roy. Do you see any option to make this horizontal? It will display much better in a paper or on a website.
> 
> My humble attempt:
> 
> ![image](https://user-images.githubusercontent.com/16557730/99790697-c5a9f900-2b24-11eb-97b6-1c8cd5d76bce.png)
> 
> We need to keep it with Arial (JM style).

I like this format better to the previous one (direction is clearer). You may want to add an explanation on when a process is considered a workflow. For example, why is data collection not a workflow? And what do the white boxes with solid lines mean?
