### ISSUE TITLE
role of GitHub

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#21]
decide on role of GitHub in this course

**Comment by RoyKlaasseBos** [comment]
Last week we discussed that for this course we would not use Github as a version control nor collaboration tool (given the available time for a 3 ECTS course). Yet, I do think we can use it as a place to host our material ("walk the talk" - TSH), and they can simply use the download button (without using the terminal etc.). As for collaboration in the team project, they can use Google Drive to share their code within the team.

On the other hand, those students who take dPREP in parallel can benefit from applying their knowledge in this course, and we may even want to encourage them to do so. For example, refer to this section on TSH as a bonus or advanced part of the course that will not be examined but may be highly beneficial.
