### ISSUE TITLE
grading rubric for team project

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#24]
- think about objective performance criteria
- cast those in a rubric

Here are a few example assignments / 
rubrics:
- [Team_Assignment_1.pdf](https://github.com/hannesdatta/course-odcm/files/5629540/Team_Assignment_1.pdf)
- [Team_Assignment_2.pdf](https://github.com/hannesdatta/course-odcm/files/5629541/Team_Assignment_2.pdf)

**Comment by RoyKlaasseBos** [comment]
There's also a filled out example in `project/evaluation_rubric.md`
