### ISSUE TITLE
Define learning goals for all tutorials

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#3]
I have pushed updates to the dev branch with three specific tutorials:
- software setup
- python bootcamp
- web scraping 101 (example, WITH apis - take out), in \src

Please work on these three tutorials, by producing text-based (bullet point style) versions of the tutorial. For python, please only gather relevant links from Datacamp.

Let's not try to be perfect in the first iteration, but rather see the first step towards a more final version.

**Comment by hannesdatta** [comment]
I updated the list of tutorials. The software installation and Python tutorials are well defined (right, @RoyKlaasseBos?) and can be developed. 

I will still have to define the content of the actual "content" tutorials before they can go under development.

**Comment by hannesdatta** [comment]
- [ ] attach files for each of the tutorials if code already exists

**Comment by hannesdatta** [comment]
Some more inspiration": https://github.com/CU-ITSS/Web-Data-Scraping-S2019

**Comment by hannesdatta** [comment]
- Please define the learning goals for the tutorials.

**Comment by hannesdatta** [comment]
Goals for cleaning up tutorials:
- "mutual exclusiveness" 
- compacted version rather than elaborate lectures/libraries of how to do things
- what's part of tutorial, and what moves to "lectures" / "modules"
-

**Comment by hannesdatta** [comment]
@RoyKlaasseBos: for tomorrow

- [ ] please draft a cleaned version of learning goals for all tutorials
- [ ] the goal is that you start developing the first three (web data; web scraping 101, API 101) from tomorrow onwards

**Comment by hannesdatta** [comment]
@hannesdatta: also check out google doc to put in some own thoughts

**Comment by RoyKlaasseBos** [comment]
Here's the [cleaned version](https://docs.google.com/document/d/1K6PLnRPmKuYC7o8yQcqaCZhzWONE40SOzhjbk9aUzBk/edit?usp=sharing) of the learning goals for the tutorials.

**Comment by RoyKlaasseBos** [comment]
> Some more inspiration": https://github.com/CU-ITSS/Web-Data-Scraping-S2019

This is the storytelling style I'd like to follow. His notebooks also contain some great references and comments about legal issues.

**Comment by hannesdatta** [comment]
@hannesdatta give feedback to roy on learning goals

**Comment by hannesdatta** [comment]
@RoyKlaasseBos, please finalize learning goals for all tutorials (101's, advanced)

**Comment by hannesdatta** [comment]
I'm closing this issue, and will comment on individual tutorials in individual issues.
