### ISSUE TITLE
decide how students track progress on learning goals

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#35]
e.g., "pulse"

**Comment by RoyKlaasseBos** [comment]
[This](https://www.sli.do/features-questions) is the type of Q&A tool I referred to: 
* Students can submit questions and upvote others' questions 
* Questions are sorted by the number of votes (like Reddit/Stackoverflow)
* Address a subset of all questions during the live lectures (which you can prepare in advance)
* Free up to 100 participants
* Not ideal for posting code snippets etc. nor very elaborate descriptions but perhaps a good place to start
