### ISSUE TITLE
add software installation to tutorial page

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#36]
![image](https://user-images.githubusercontent.com/16557730/102607464-a3f26080-4128-11eb-8896-d5b37222ec7c.png)

--> http://127.0.0.1:1313/docs/tutorials/software/

Add content from slide deck / link to Tilburg Science Hub to page.

Goal: page should be viewable soon.

**Comment by RoyKlaasseBos** [comment]
I've updated the software page with the links. Now working on the Python Bootcamp tutorial that covers the "missing pieces"
