### ISSUE TITLE
open edu logo?

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#42]
Hi Andrea,

could you please think about a quick way to energise this logo a bit? The notion needs to be that this is TilburgU, but open! Like Tilburg University (with a small text): open education? Or something like this? Buzzy, marketing-ish. Would be cool if you could think about it for a minute or so ;).

<img width="445" alt="image" src="https://user-images.githubusercontent.com/16557730/104151355-1cbda300-53dd-11eb-8129-7cbddcceeb2b.png">

**Comment by hannesdatta** [comment]
@andreantonacci, any quick inspiration on extending the TiU logo with something that shows this is an open education course?

![image](https://user-images.githubusercontent.com/16557730/106298260-f9f01300-6253-11eb-959f-dff55c219aec.png)

If you're in the designer mode, I'm curious to hear your suggestions.

**Comment by andreantonacci** [comment]
I'm on it
