### ISSUE TITLE
Collection of scraping and API examples

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#5]
The example section in `dev` will feature links and short descriptions to publicly available scrapers and APIs.

Please collect and organize these links. The main goal is to offer students a starting point to get inspired for their own projects.

Possible content headers are:
- Code/repositories
  - Web scraping projects with code
  - API data retrieval projects with code
- Tools used for web scraping
- Other tutorials on the web
...

Think broadly about useful categories, and then please browse the web for inspiration. Issue #2 has a couple of links already.

**Comment by RoyKlaasseBos** [comment]
## Web Scraping Sites
* https://www.boxofficemojo.com/
* https://www.sports-reference.com/
* http://quotes.toscrape.com

## Tutorials
* https://www.youtube.com/watch?v=RUQWPJ1T6Zc&t=190s
* https://www.youtube.com/watch?v=Mw-dsY8UKVs
