### ISSUE TITLE
add to web data advanced

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#50]
Web data advanced currently shows how to scroll through the entire page.

Yet, it may be super useful for students to learn how to only scroll "once", or "twice", or a little bit. 

Please add a little section to the tutorial where this is done (inspiration can be find in students' project submissions).

**Comment by RalphGit21** [comment]
From Stackoverflow, should work for twitter as well:

SCROLL_PAUSE_TIME = 0.5

# Get scroll height
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # Scroll down to bottom
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # Wait to load page
    time.sleep(SCROLL_PAUSE_TIME)

    # Calculate new scroll height and compare with last scroll height
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

**Comment by hannesdatta** [comment]
Try out & add to tutorial?

**Comment by hannesdatta** [comment]
Try out on a different website and then add to tutorial.

**Comment by RalphGit21** [comment]
Tested in the tutorial and works - Not sure how to implement this in google colab (may be due to access rights)

**Comment by hannesdatta** [comment]
please still add to the tutorial & commit
