### ISSUE TITLE
Content of team project

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#7]
Define broadly the content of the team project.

**Comment by RoyKlaasseBos** [comment]
As I mentioned earlier, I think it would be good practise to structure the team projects a bit more. [Here's](https://github.com/kimfetti/Conferences/blob/master/PyCon_2020/mini_project_ideas.md) an example of what I mean: a site followed by a list of potential research ideas. With regards to this course, we may want to ask students to submit all their business/academic research ideas before the lecture in week 2 -> group them by category and site -> curate and validate the most interesting ideas -> publish those as a source of inspiration for students.

**Comment by RoyKlaasseBos** [comment]
Grading matrix for team projects which we can share upfront

**Comment by hannesdatta** [comment]
potentially:
- reddit
- chartmetric

scraping:
- social blade [bs]
- spotify web player [selenium]
- Netflix [selenium]
