### ISSUE TITLE
update specification matrix

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#82]
SurfDrive contains a new specification matrix in the spring 2022 folder for oDCM. I have completed the tab for the exam.

**Please update the assignment tab, by updating the learning goals like i have formulated and numbered them in the exams tab.** You will probably have to shift around witht he percentages (summing some). Can you update the main document directly on SurfDrive, please (xlsx)?

Updated learning goals for "exam" part:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/16557730/156140667-9e8338bb-6f1e-4c21-a300-72d8376cd9a1.png">

Old learnign goals for assignment that need to be updated:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/16557730/156140712-24631d23-88c2-4189-a982-2f1aa02c409c.png">

Please also update the percentages in grading, if necessary:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/16557730/156140774-25cdb7ab-222c-4758-97f2-73da1d2ba82c.png">

Please also add a tab for the "pulse" part (5%) - prob falls in category 6 learning goal (track, evaluate, and share [...])

**Comment by RalphGit21** [comment]
See odcm folder on surfdrive
