### ISSUE TITLE
Tutorial dev: Python bootcamp

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#9]
Please develop a Jupyter Notebook that teaches students the learning goals laid out in the Tutorial page on Python Bootcamp.

Note: you do not have to develop material from scratch, but can also make use of available material. If that material is available OO, we can integrate it in our own notebooks. You could also think about linking to datacamp courses first. 

Also recall our discussion:
- Mandatory Notebook that we designed
- Mandatory Datacamp courses (decide about order)
- Optional courses.

**Comment by hannesdatta** [comment]
@RoyKlaasseBos, maybe use (updated?) material available on jupyterlab for this? do you have access?

![image](https://user-images.githubusercontent.com/16557730/99511094-1c2e0080-2988-11eb-804d-6daeb3c2bef0.png)

**Comment by hannesdatta** [comment]
you could also email the course coordinator for updated material. the version here is 2018. 
![image](https://user-images.githubusercontent.com/16557730/99511225-48e21800-2988-11eb-8719-094a45df9b07.png)

**Comment by RoyKlaasseBos** [comment]
Python Bootcamp: https://app.pitch.com/app/presentation/2eef8fbf-2f09-4a09-b90e-d22f1e63ca84/9bd2556b-7f5b-4d6a-b096-13baca5945c4 

Self-assessment example: https://github.com/RoyKlaasseBos/self-study-resources/blob/master/DSI-Self-Assessment.pdf
