### ISSUE TITLE
make example projects more prominent + add best ones of this year

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#91]
have NEW subsection called "past projects" w/ a little introduction text, plus DIRECT links to each of these projects 

e.g., Scraping GitHub for blabla (should be mentioned as API vs. scraping) --> direct link to zenodo

Further, MAKE available on Surf a NEW example collection of this year which @hannesdatta can upload to Zenodo (anonymization of some names)

**Comment by RalphGit21** [comment]
Choose 3/4 best new ones from previous semester

**Comment by RalphGit21** [comment]
On surfdrive, see odcm03 > projects > past project

This includes 3 (unzipped) projects from previous semester that scored an 8 or higher. The data folders are removed from the folders as well. These can be uploaded to Zenodo (after which I will put them on the site)

**Comment by hannesdatta** [comment]
Ralph adds Twitch & Mediamarkt, @hannesdatta uploads to Zenodo.
