### ISSUE TITLE
propose new session plan & discuss w/ Ralph

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#94]
@RalphGit21: make schedule draft in Excel

+ think about what to offer online and what to offer offline

GOALS:

1) align course w/ PAPER & project

(let students READ parts of the paper & make active use of the tables as a kind of cheat sheet)

> So for example, first lecture on how
to choose a good website for scraping, second
lecture on methods (e.g. selenium vs
beautifulsoup) and which one to choose. Next
lecture on loading packages and staring with the
project (e.g seed generation), next lecture on
scraping content etc. So that each lecture would
show step by step on how to build a scraper and it
could interactive that students have to say ideas
for the code and we would discuss why this and
not that approach is better. I think that would help
us to understand the logic behind Python.

2) allocate more time to coaching sessions

3) plan in detail the "live stream" lectures so that content does not depend purely on Pulse

**Comment by RalphGit21** [comment]
See file on surfdrive > odcm 4 fall
