### ISSUE TITLE
door de page lopen & updaten

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/course-odcm#97]
- suggest "simple" changes to the site which make it better navigable
- reduce redundancies (e.g., stuff that's mentioned twice, rather link to it)
- always use up-to-date references to paper FIELDS OF GOLD (now published at JM) -0-> doi.org/XXXXXXXXXXXX
- remove old exam dates etc. and make page be "up-to-date"

**Comment by RalphGit21** [comment]
Change "team project"  and "exam" contents that are now in course "folder"  to the "main folder". That is, students do not have to click on course first to then navigate to team project and further (takes a lot of clicks and team project and exam contents will be searched for often).
